### ISSUE TITLE
Create functionality to hide sidebar

### ISSUE THREAD

**Issue by MarcSkovMadsen** [MarcSkovMadsen/awesome-panel#12]
#### My pain

Sometimes you don't wan't to take up screen space on the sidebar. For example on mobile devices.

#### Solution

Create a "button" and functionality to hide/ show the sidebar.

![image](https://user-images.githubusercontent.com/42288570/70853706-d207e980-1eb1-11ea-8cdf-93cfaa675b48.png)

**Comment by AntonBiryukovUofC** [comment]
The hamburger icon though works with the Templates...

**Comment by MarcSkovMadsen** [comment]
No longer relevant
