### ISSUE TITLE
s/powerfull/powerful/g

### ISSUE THREAD

**Issue by eriknw** [MarcSkovMadsen/awesome-panel#22]
I noticed the typo "powerfull" is used lots of places.  Is this typo intentional?  Should be "powerful".

**Comment by MarcSkovMadsen** [comment]
I think it’s just me. English is not my first language. 

My mother was an English teacher, so she will not be happy? 😉

Thanks.

**Comment by MarcSkovMadsen** [comment]
Has been solved. So I closed this one.
