### ISSUE TITLE
Update git setting per repo

### ISSUE THREAD

**Issue by Hoxbro** [MarcSkovMadsen/awesome-panel#28]
Hi Marc. 

I don't know the best way to do this, but I have seen that your commits usually have multiple mails connected to it. I assume this is related to the global git setting being setup to your work mail and your Github account is setup to your private mail.  You can change the config setting for each local git repo with the following commands:
```
git config user.name "YOUR_NAME"
git config user.email "YOUR_GITHUB_MAIL"
```

**Comment by MarcSkovMadsen** [comment]
Thanks @Hoxbro . I've applied it to the three Panel repositories I have. Let me know if you don't see the change. Thanks.

I can see you are pretty active with Panel. If you want to connect I would really like to. You can do so at https://www.linkedin.com/in/marcskovmadsen/.
